[project]
name = "dronerf"
version = "0.1.0"
description = "Add your description here"
readme = "README"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.1",
    "torch>=2.13.0",
    "tqdm>=4.70.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
